name: core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.3
  equatable: ^1.2.3
  gson: ^0.1.4
  network:
    path: ../network
  values:
    path: ../values
  widgets:
    path: ../widgets



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
